### PR TITLE
Separate ROI volumes

### PR DESCRIPTION
**Pull request by tbaudier**
The modification allow to take into account tag inside dicom sequence

### CODE REVIEW

**Comment by tbaudier** [comment]
I updated the notebook and pivot files to take into account radiomics

**Review by VincentLeTexier — APPROVED** [review]

**Comment by VincentLeTexier** [comment]
- OSIRIS_pivot_RadiomicsCriteria.csv
modify RadiomicsCriteria_Method to RadiomicsCriteria_ComputationalLocalisationMethod
add RadiomicsCriteria_CalculationWindowMatrix
add UsedImageFilterParameters
add RadiomicsCriteria_DiscretisationMethod      
add RadiomicsCriteria_BiggestIntensity
remove RadiomicsCriteria_NumberOfGreyLevels

**Comment by VincentLeTexier** [comment]
- OSIRIS_pivot_RadiomicsImageFilter.csv
c'est un EAV 
DONC : 
Patient_Id, Instance_Id, ROISegmentation_Ref,RadiomicsFeature_Id,RadiomicsFeature_Name,RadiomicsFeature_Value
1,1,499,0, original_shape_Elongation, 0.9124894758560576
1,1,499,0, original_shape_Flatness, 0.7917742474372075
1,1,499,0, original_shape_LeastAxisLength, 13.649792818357856
...
On ne connait pas l'IBSI_ID (j'ai mis 0 pour le moment)

Il faudrait voir comment standardiser cela. Chaque logiciel donne un liste de variables, lien avec la norme IBSI ?

**Comment by tbaudier** [comment]
Here: https://github.com/siric-osiris/OSIRIS/pull/23 

> * OSIRIS_pivot_PatientStudy.csv
>   remove Series_Size
>   remove Series_Weight
>   add Analysis_ref (put a random number)

I do not create PatientStudy pivot for the moment. It's not in the doc
https://github.com/siric-osiris/OSIRIS/tree/MED-OSIRIS/documentation/ModeleImagerieOSIRIS.pdf

> * OSIRIS_pivot_Equipment.csv :
>   Add Equipment_SoftwareVersion
>   Remove Series_Ref

done

> * OSIRIS_pivot_Study.csv :
>   add Study_AcquisitionDate
>   add PatientStudy_Ref
>   remove Study_StorePlace

done except PatientStudy_Ref

> * OSIRIS_pivot_Series.csv :
>   add Equipment_Ref
>   remove Series_SoftwareVersion
>   modify Series_PatientHeigh  to Series_PatientSize

done

> * OSIRIS_pivot_RadiomicsCriteria.csv
> modify RadiomicsCriteria_Method to RadiomicsCriteria_ComputationalLocalisationMethod
> add RadiomicsCriteria_CalculationWindowMatrix
> add UsedImageFilterParameters
> add RadiomicsCriteria_DiscretisationMethod
> add RadiomicsCriteria_BiggestIntensity
> remove RadiomicsCriteria_NumberOfGreyLevels

done

> * OSIRIS_pivot_RadiomicsImageFilter.csv
> modify RadiomicsImageFilter_FilterName to RadiomicsImageFilter_FilterMethod

done

**Pull request merged**
